export const verifiedGiphyGameChannels = [
  "@fortnite",
  "@playoverwatch",
  "@leagueoflegends",
  "@minecraft",
  "@callofduty",
  "@pokemon",
  "@playapex",
  "@easportsfc",
  "@warcraftmovie",
  "@pubg",
  "@thesims",
  "@brawlstars",
  "@everdale",
  "@fallguysgame",
  "@halo",
  "@assassinscreed",
  "@battlefield",
  "@farcrygame",
  "@playvalorant",
  "@fnafmovie",
  "@seaofthieves",
  "@deadbydaylight",
  "@borderlands",
  "@destinythegame",
  "@playdiablo",
  "@xbox",
  "@playstation",
  "@ubisoft",
  "@blizzard",
  "@rockstargames",
  "@squareenix",
  "@sega",
  "@naughty_dog",
];

export const arrayOfRandomAvatarGifs = [
  "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGhyZHZyZDFyeml3N3p2dnBjZmg0bHl4a2JhM3hrZ3ZxNXQ3ZnRwaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9lHsP26ijVJwylXsff/giphy.gif",
  "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbm8wM3lzYTcwaXBhZnJhMHc5N210NjR3ajJ6cnQ3dmg3ZnQ4a3V3eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/dKCY50ptJQQpBTLahd/giphy.gif",
  "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnJsNjhmaGh6cHY3c3BoMW1jNGQ1bmE2NWoxOXZkMnEwNzFjZ2QzbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tP7U30CtAGOplr02dk/giphy.gif",
  "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExemkyZm52Ym9pam1reDdrNWRxeXRtaHBuZ20wcXpjZWVwcjRvNjdwNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xvRPIAtMwKQ2SlxKtx/giphy.gif",
  //TODO: Add more giphy gifs for authenticated users.
];
